---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-bot
  namespace: monitoring
  labels:
    app: alertmanager-bot
    collect-metrics: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    name: metrics
    targetPort: 8080
  selector:
    app: alertmanager-bot

